fix: use `onApplicationShutdown` to disconnect kafka producers
Byndyusoft/nest-kafka pull request #135
Opened 2024-09-02 02:27 UTC by vglebovich-lmru

2024-09-02 02:28 UTC, vglebovich-lmru commented
@KillWolfVlad please take a look

2024-09-02 07:15 UTC, KillWolfVlad submitted a review, later dismissed

2024-09-04 11:52 UTC, KillWolfVlad requested changes

2024-09-04 11:52 UTC, KillWolfVlad commented on README.md
> +  await app.listen(...)
Неправильный порядок запуска в README. Лучше всего располагать startAllMicroservices после listen.

2024-09-04 12:23 UTC, vglebovich-lmru commented on README.md
> +  await app.listen(...)
Исправил

2024-09-04 12:25 UTC, KillWolfVlad approved these changes

2024-09-04 12:29 UTC, merged